before:
  hooks:
    - go mod tidy
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
archives:
  -
    replacements:
      darwin: macOS
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
    format_overrides:
      - goos: windows
        format: zip
    files:
      - LICENSE

checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

brews:
  - tap:
      owner: ismaelpadilla
      name: homebrew-tap
    commit_msg_template: "{{ .ProjectName }}: Update formula to {{ .Tag }}"
    commit_author:
      name: Ismael Padilla
      email: padillaismael92@gmail.com
    homepage: https://github.com/ismaelpadilla/gotorrent
    description: "TUI for searching torrents"
    license: "AGPL-3.0"
    skip_upload: auto


aurs:
  - name: gotorrent
    homepage: "https://github.com/ismaelpadilla/gotorrent"
    description: "TUI for searching torrents"
    maintainers:
      - 'Ismael Padilla <padillaismael92@gmail.com>'
    license: "AGPL-3.0"
    private_key: "{{ .Env.AUR_KEY }}"
    git_url: 'ssh://aur@aur.archlinux.org/gotorrent-bin.git'
    package: |-
      # bin
      install -Dm755 "./mybin" "${pkgdir}/usr/bin/mybin"

      # license
      install -Dm644 "./LICENSE" "${pkgdir}/usr/share/licenses/mybin/LICENSE"
    commit_author:
      name: Ismael Padilla
      email: padillaismael92@gmail.com
    commit_msg_template: "pkgbuild updates"
    skip_upload: auto
